package AnaSayfa;

import javax.swing.JFrame;
import javax.swing.JTextField;

public class AnaSayfa extends javax.swing.JFrame {

    int mousepressx;
    int mousepressy;

    public AnaSayfa() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Anasayfa_Panel = new javax.swing.JPanel();
        textKullaniciAdi = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        fotoKaldırma = new javax.swing.JLabel();
        Personel_Sayfasi = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        envanterPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        mhareket = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        profilim = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();
        personel_cikis = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        kaldırmaa = new javax.swing.JLabel();
        Amir_sayfasi = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        a_env_list_buton = new javax.swing.JLabel();
        a_personeller_buton = new javax.swing.JLabel();
        a_pers_mal_harek_but = new javax.swing.JLabel();
        a_malzeme_hareket = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        amir_mainpanel = new javax.swing.JPanel();
        amir_envanter_listesi = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        amir_personeller = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        amir_pers_mal_hareket = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        amir_malz_hareket = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        kaldırmas = new javax.swing.JLabel();
        amir_cikis_sayfasi = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        kaldırmaa1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 150));
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Anasayfa_Panel.setPreferredSize(new java.awt.Dimension(1080, 720));
        Anasayfa_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textKullaniciAdi.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        textKullaniciAdi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textKullaniciAdi.setText("ID Giriniz");
        textKullaniciAdi.setBorder(null);
        textKullaniciAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textKullaniciAdiMouseClicked(evt);
            }
        });
        Anasayfa_Panel.add(textKullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 385, 190, 50));

        jPasswordField1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("Şifre Giriniz");
        jPasswordField1.setBorder(null);
        jPasswordField1.setPreferredSize(new java.awt.Dimension(190, 50));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        Anasayfa_Panel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        Anasayfa_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 24));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/switch-off.png"))); // NOI18N
        jLabel2.setToolTipText("KAPAT");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Anasayfa_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/user (1).png"))); // NOI18N
        Anasayfa_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 393, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/key (1).png"))); // NOI18N
        Anasayfa_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 468, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/eye.png"))); // NOI18N
        jLabel5.setToolTipText("Şifreyi Gör");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        Anasayfa_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 473, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/fast-forward.png"))); // NOI18N
        jLabel6.setToolTipText("GİRİŞ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        Anasayfa_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 105, 166));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("PERSONEL");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        Anasayfa_Panel.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 90, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 105, 166));
        jRadioButton2.setText("AMİR");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.setOpaque(false);
        Anasayfa_Panel.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        fotoKaldırma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GirisFoto/DEPOSİS (1).png"))); // NOI18N
        fotoKaldırma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 105, 166), 2));
        fotoKaldırma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fotoKaldırmaMouseClicked(evt);
            }
        });
        Anasayfa_Panel.add(fotoKaldırma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        getContentPane().add(Anasayfa_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        Personel_Sayfasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Personel_Sayfasi.setPreferredSize(new java.awt.Dimension(1080, 720));
        Personel_Sayfasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        envanterPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 105, 166));
        jLabel10.setText("Envanter Listesi");
        envanterPanel.add(jLabel10);

        mainPanel.add(envanterPanel, "card2");

        mhareket.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 105, 166));
        jLabel11.setText("Malzeme Hareketliliği");
        mhareket.add(jLabel11);

        mainPanel.add(mhareket, "card3");

        profilim.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 105, 166));
        jLabel14.setText("Profilim");
        profilim.add(jLabel14);

        mainPanel.add(profilim, "card4");

        Personel_Sayfasi.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 670, 430));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 105, 166));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/envanter listesi.png"))); // NOI18N
        jLabel8.setText("   Envanter Listesi");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        Personel_Sayfasi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 190, 64));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 105, 166));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/malzeme hareketliliği.png"))); // NOI18N
        jLabel9.setText("   Malzeme Hareketliliği");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        Personel_Sayfasi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, 64));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/home.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        Personel_Sayfasi.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, -1, -1));

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        Personel_Sayfasi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 24));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 105, 166));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/kisi bilgiai.png"))); // NOI18N
        jLabel13.setText("   Profilim");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setMaximumSize(new java.awt.Dimension(64, 64));
        jLabel13.setMinimumSize(new java.awt.Dimension(64, 64));
        jLabel13.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        Personel_Sayfasi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 220, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/switch-off.png"))); // NOI18N
        jLabel15.setToolTipText("KAPAT");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        Personel_Sayfasi.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, -1, -1));

        wall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GirisFoto/Deposis Giriş Ekranı.png"))); // NOI18N
        wall.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 105, 166), 2));
        Personel_Sayfasi.add(wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        getContentPane().add(Personel_Sayfasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        personel_cikis.setMinimumSize(new java.awt.Dimension(1080, 720));
        personel_cikis.setPreferredSize(new java.awt.Dimension(1080, 720));
        personel_cikis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 105, 166));
        jLabel17.setText("Uygulamayı Kapatmak İstiyor Musunuz?");
        personel_cikis.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 320, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/error.png"))); // NOI18N
        personel_cikis.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 185, -1, -1));

        jLabel18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel18MouseDragged(evt);
            }
        });
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        personel_cikis.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 24));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 105, 166));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/close.png"))); // NOI18N
        jLabel19.setText("Hayır   ");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        personel_cikis.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 80, 40));

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 105, 166));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/check.png"))); // NOI18N
        jLabel20.setText("Evet   ");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        personel_cikis.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 240, 80, 40));

        kaldırmaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GirisFoto/Deposis Giriş Ekranı.png"))); // NOI18N
        kaldırmaa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 105, 166), 2));
        personel_cikis.add(kaldırmaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        getContentPane().add(personel_cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        Amir_sayfasi.setMinimumSize(new java.awt.Dimension(1080, 720));
        Amir_sayfasi.setPreferredSize(new java.awt.Dimension(1080, 720));
        Amir_sayfasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel22MouseDragged(evt);
            }
        });
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        Amir_sayfasi.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 24));

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 105, 166));
        jLabel21.setText("Malzeme");
        Amir_sayfasi.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        a_env_list_buton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        a_env_list_buton.setForeground(new java.awt.Color(0, 105, 166));
        a_env_list_buton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/envanter listesi.png"))); // NOI18N
        a_env_list_buton.setText("   Envanter Listesi");
        a_env_list_buton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_env_list_butonMouseClicked(evt);
            }
        });
        Amir_sayfasi.add(a_env_list_buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 190, 64));

        a_personeller_buton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        a_personeller_buton.setForeground(new java.awt.Color(0, 105, 166));
        a_personeller_buton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/personel.png"))); // NOI18N
        a_personeller_buton.setText("   Personeller");
        a_personeller_buton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_personeller_butonMouseClicked(evt);
            }
        });
        Amir_sayfasi.add(a_personeller_buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 190, 64));

        a_pers_mal_harek_but.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        a_pers_mal_harek_but.setForeground(new java.awt.Color(0, 105, 166));
        a_pers_mal_harek_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/kişilerin malzeme hareketliliği.png"))); // NOI18N
        a_pers_mal_harek_but.setText("   Personellerin");
        a_pers_mal_harek_but.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        a_pers_mal_harek_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_pers_mal_harek_butMouseClicked(evt);
            }
        });
        Amir_sayfasi.add(a_pers_mal_harek_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 190, 64));

        a_malzeme_hareket.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        a_malzeme_hareket.setForeground(new java.awt.Color(0, 105, 166));
        a_malzeme_hareket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/malzeme hareketliliği.png"))); // NOI18N
        a_malzeme_hareket.setText("   Malzeme Hareketliliği");
        a_malzeme_hareket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_malzeme_hareketMouseClicked(evt);
            }
        });
        Amir_sayfasi.add(a_malzeme_hareket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 220, 64));

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 105, 166));
        jLabel23.setText("Hareketliliği");
        Amir_sayfasi.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        amir_mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        amir_mainpanel.setLayout(new java.awt.CardLayout());

        amir_envanter_listesi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 105, 166));
        jLabel24.setText("Envanter Listesi");
        amir_envanter_listesi.add(jLabel24);

        amir_mainpanel.add(amir_envanter_listesi, "card2");

        amir_personeller.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 105, 166));
        jLabel25.setText("Personeller");
        amir_personeller.add(jLabel25);

        amir_mainpanel.add(amir_personeller, "card3");

        amir_pers_mal_hareket.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 105, 166));
        jLabel26.setText("Personellerin Malzeme Hareketliliği");
        amir_pers_mal_hareket.add(jLabel26);

        amir_mainpanel.add(amir_pers_mal_hareket, "card4");

        amir_malz_hareket.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 105, 166));
        jLabel27.setText("Malzeme Hareketliliği");
        amir_malz_hareket.add(jLabel27);

        amir_mainpanel.add(amir_malz_hareket, "card5");

        Amir_sayfasi.add(amir_mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 670, 430));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/home.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        Amir_sayfasi.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/switch-off.png"))); // NOI18N
        jLabel29.setToolTipText("KAPAT");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        Amir_sayfasi.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, -1, -1));

        kaldırmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GirisFoto/Deposis Giriş Ekranı.png"))); // NOI18N
        kaldırmas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 105, 166), 2));
        Amir_sayfasi.add(kaldırmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        getContentPane().add(Amir_sayfasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        amir_cikis_sayfasi.setMinimumSize(new java.awt.Dimension(1080, 720));
        amir_cikis_sayfasi.setPreferredSize(new java.awt.Dimension(1080, 720));
        amir_cikis_sayfasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel30MouseDragged(evt);
            }
        });
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel30MousePressed(evt);
            }
        });
        amir_cikis_sayfasi.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 24));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/error.png"))); // NOI18N
        amir_cikis_sayfasi.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 185, -1, -1));

        jLabel32.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 105, 166));
        jLabel32.setText("Uygulamayı Kapatmak İstiyor Musunuz?");
        amir_cikis_sayfasi.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 320, -1));

        jLabel33.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 105, 166));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/check.png"))); // NOI18N
        jLabel33.setText("Evet   ");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        amir_cikis_sayfasi.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 240, 80, 40));

        jLabel34.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 105, 166));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HareketIcons/close.png"))); // NOI18N
        jLabel34.setText("Hayır   ");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        amir_cikis_sayfasi.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 80, 40));

        kaldırmaa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GirisFoto/Deposis Giriş Ekranı.png"))); // NOI18N
        kaldırmaa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 105, 166), 2));
        amir_cikis_sayfasi.add(kaldırmaa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        getContentPane().add(amir_cikis_sayfasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textKullaniciAdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textKullaniciAdiMouseClicked
        if (textKullaniciAdi.getText().equals("ID Giriniz")) {
            textKullaniciAdi.setText("");
        }
        if (jPasswordField1.getText().equals("")) {
            jPasswordField1.setText("Şifre Giriniz");
        }
    }//GEN-LAST:event_textKullaniciAdiMouseClicked

    private void fotoKaldırmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotoKaldırmaMouseClicked
        if (textKullaniciAdi.getText().equals("")) {
            textKullaniciAdi.setText("ID Giriniz");
        }
        if (jPasswordField1.getText().equals("")) {
            jPasswordField1.setText("Şifre Giriniz");
        }
    }//GEN-LAST:event_fotoKaldırmaMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        if (jPasswordField1.getText().equals("Şifre Giriniz")) {
            jPasswordField1.setText("");
        }
        if (textKullaniciAdi.getText().equals("")) {
            textKullaniciAdi.setText("ID Giriniz");
        }
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        mousepressx = evt.getX();
        mousepressy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int kordinatx = evt.getXOnScreen();
        int kordinaty = evt.getYOnScreen();
        this.setLocation(kordinatx - mousepressx, kordinaty - mousepressy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        jPasswordField1.setEchoChar((char) 0);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        jPasswordField1.setEchoChar('•');
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);


    }//GEN-LAST:event_jLabel2MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (textKullaniciAdi.getText().equals("ID Giriniz") & jPasswordField1.getText().equals("Şifre Giriniz")) {
            if (jRadioButton1.isSelected()) {
                Anasayfa_Panel.setVisible(false);
                Personel_Sayfasi.setVisible(true);

            }
            if (jRadioButton2.isSelected()) {
                Anasayfa_Panel.setVisible(false);
                Personel_Sayfasi.setVisible(false);
                personel_cikis.setVisible(false);
                Amir_sayfasi.setVisible(true);
            }
        }

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        //panel silme
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //panel ekleme
        mainPanel.add(envanterPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        //panel silme
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //panel ekleme
        mainPanel.add(mhareket);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Personel_Sayfasi.setVisible(false);

        textKullaniciAdi.setText("ID Giriniz");
        jPasswordField1.setText("Şifre Giriniz");

        Anasayfa_Panel.setVisible(true);


    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int kordinatx = evt.getXOnScreen();
        int kordinaty = evt.getYOnScreen();
        this.setLocation(kordinatx - mousepressx, kordinaty - mousepressy);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        mousepressx = evt.getX();
        mousepressy = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        //panel silme
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        //panel ekleme
        mainPanel.add(profilim);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        personel_cikis.setVisible(true);
        Personel_Sayfasi.setVisible(false);
        Anasayfa_Panel.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel18MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseDragged
        int kordinatx = evt.getXOnScreen();
        int kordinaty = evt.getYOnScreen();
        this.setLocation(kordinatx - mousepressx, kordinaty - mousepressy);
    }//GEN-LAST:event_jLabel18MouseDragged

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        mousepressx = evt.getX();
        mousepressy = evt.getY();
    }//GEN-LAST:event_jLabel18MousePressed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        Anasayfa_Panel.setVisible(false);
        personel_cikis.setVisible(false);
        Personel_Sayfasi.setVisible(true);

    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel22MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseDragged
        int kordinatx = evt.getXOnScreen();
        int kordinaty = evt.getYOnScreen();
        this.setLocation(kordinatx - mousepressx, kordinaty - mousepressy);
    }//GEN-LAST:event_jLabel22MouseDragged

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        mousepressx = evt.getX();
        mousepressy = evt.getY();
    }//GEN-LAST:event_jLabel22MousePressed

    private void a_env_list_butonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_env_list_butonMouseClicked
          //panel silme
        amir_mainpanel.removeAll();
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();

        //panel ekleme
        amir_mainpanel.add(amir_envanter_listesi);
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();
    }//GEN-LAST:event_a_env_list_butonMouseClicked

    private void a_personeller_butonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_personeller_butonMouseClicked
          //panel silme
        amir_mainpanel.removeAll();
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();

        //panel ekleme
        amir_mainpanel.add(amir_personeller);
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();
    }//GEN-LAST:event_a_personeller_butonMouseClicked

    private void a_pers_mal_harek_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_pers_mal_harek_butMouseClicked
          //panel silme
        amir_mainpanel.removeAll();
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();

        //panel ekleme
        amir_mainpanel.add(amir_pers_mal_hareket);
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();
    }//GEN-LAST:event_a_pers_mal_harek_butMouseClicked

    private void a_malzeme_hareketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_malzeme_hareketMouseClicked
          //panel silme
        amir_mainpanel.removeAll();
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();

        //panel ekleme
        amir_mainpanel.add(amir_malz_hareket);
        amir_mainpanel.repaint();
        amir_mainpanel.revalidate();
    }//GEN-LAST:event_a_malzeme_hareketMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        Anasayfa_Panel.setVisible(true);
        Amir_sayfasi.setVisible(false);
        personel_cikis.setVisible(false);
        Personel_Sayfasi.setVisible(false);
        
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        amir_cikis_sayfasi.setVisible(true);
        Amir_sayfasi.setVisible(false);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseDragged
        int kordinatx = evt.getXOnScreen();
        int kordinaty = evt.getYOnScreen();
        this.setLocation(kordinatx - mousepressx, kordinaty - mousepressy);
    }//GEN-LAST:event_jLabel30MouseDragged

    private void jLabel30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MousePressed
        mousepressx = evt.getX();
        mousepressy = evt.getY();
    }//GEN-LAST:event_jLabel30MousePressed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        amir_cikis_sayfasi.setVisible(false);
        Amir_sayfasi.setVisible(true);
    }//GEN-LAST:event_jLabel34MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Amir_sayfasi;
    private javax.swing.JPanel Anasayfa_Panel;
    private javax.swing.JPanel Personel_Sayfasi;
    private javax.swing.JLabel a_env_list_buton;
    private javax.swing.JLabel a_malzeme_hareket;
    private javax.swing.JLabel a_pers_mal_harek_but;
    private javax.swing.JLabel a_personeller_buton;
    private javax.swing.JPanel amir_cikis_sayfasi;
    private javax.swing.JPanel amir_envanter_listesi;
    private javax.swing.JPanel amir_mainpanel;
    private javax.swing.JPanel amir_malz_hareket;
    private javax.swing.JPanel amir_pers_mal_hareket;
    private javax.swing.JPanel amir_personeller;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel envanterPanel;
    private javax.swing.JLabel fotoKaldırma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel kaldırmaa;
    private javax.swing.JLabel kaldırmaa1;
    private javax.swing.JLabel kaldırmas;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mhareket;
    private javax.swing.JPanel personel_cikis;
    private javax.swing.JPanel profilim;
    private javax.swing.JTextField textKullaniciAdi;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
